compatibility_date = "2024-06-03"

name = "site-poketools"
pages_build_output_dir = "site"

[[d1_databases]]
binding = "db"
database_name = "d1-test"
database_id = "58d243fa-8e97-41cd-9053-f3169f54fad1"
